# Generated by Django 2.2.16 on 2022-12-07 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221207_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введено некорректное имя пользователя.', regex='^[\\w.@+-]+\\z')], verbose_name='Юзернейм'),
        ),
    ]
